# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Browser(object):
    def setupUi(self, Browser):
        Browser.setObjectName("Browser")
        Browser.resize(1035, 776)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/JHUuiS-J27Y.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Browser.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Browser)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_back = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_back.setMinimumSize(QtCore.QSize(31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/free-icon-left-arrow-271218.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_back.setIcon(icon1)
        self.toolButton_back.setObjectName("toolButton_back")
        self.gridLayout.addWidget(self.toolButton_back, 0, 0, 1, 1)
        self.toolButton_refresh = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_refresh.setMinimumSize(QtCore.QSize(31, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/free-icon-refresh-271224.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_refresh.setIcon(icon2)
        self.toolButton_refresh.setObjectName("toolButton_refresh")
        self.gridLayout.addWidget(self.toolButton_refresh, 0, 1, 1, 1)
        self.toolButton_home = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_home.setMinimumSize(QtCore.QSize(31, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/free-icon-up-arrow-271238.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_home.setIcon(icon3)
        self.toolButton_home.setObjectName("toolButton_home")
        self.gridLayout.addWidget(self.toolButton_home, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.toolButton_search = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_search.setMinimumSize(QtCore.QSize(31, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icon/free-icon-left-arrow-271236.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_search.setIcon(icon4)
        self.toolButton_search.setObjectName("toolButton_search")
        self.gridLayout.addWidget(self.toolButton_search, 0, 4, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 5)
        Browser.setCentralWidget(self.centralwidget)

        self.retranslateUi(Browser)
        QtCore.QMetaObject.connectSlotsByName(Browser)

    def retranslateUi(self, Browser):
        _translate = QtCore.QCoreApplication.translate
        Browser.setWindowTitle(_translate("Browser", "YFenBrowser"))
        self.toolButton_back.setText(_translate("Browser", "..."))
        self.toolButton_refresh.setText(_translate("Browser", "..."))
        self.toolButton_refresh.setShortcut(_translate("Browser", "F5"))
        self.toolButton_home.setText(_translate("Browser", "..."))
        self.lineEdit.setPlaceholderText(_translate("Browser", "Поиск"))
        self.toolButton_search.setText(_translate("Browser", "..."))
        self.toolButton_search.setShortcut(_translate("Browser", "Return"))
import icons_rc
