# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Browser(object):
    def setupUi(self, Browser):
        Browser.setObjectName("Browser")
        Browser.resize(903, 554)
        self.centralwidget = QtWidgets.QWidget(Browser)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton_back = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_back.setGeometry(QtCore.QRect(10, 10, 31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/free-icon-left-arrow-271218.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_back.setIcon(icon)
        self.toolButton_back.setObjectName("toolButton_back")
        self.toolButton_home = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_home.setGeometry(QtCore.QRect(70, 10, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/free-icon-up-arrow-271238.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_home.setIcon(icon1)
        self.toolButton_home.setObjectName("toolButton_home")
        self.toolButton_back_refresh = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_back_refresh.setGeometry(QtCore.QRect(40, 10, 31, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/free-icon-refresh-271224.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_back_refresh.setIcon(icon2)
        self.toolButton_back_refresh.setObjectName("toolButton_back_refresh")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 10, 741, 31))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton_search = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_search.setGeometry(QtCore.QRect(860, 10, 31, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/free-icon-left-arrow-271236.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_search.setIcon(icon3)
        self.toolButton_search.setObjectName("toolButton_search")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 50, 881, 501))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border: 1px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        Browser.setCentralWidget(self.centralwidget)

        self.retranslateUi(Browser)
        QtCore.QMetaObject.connectSlotsByName(Browser)

    def retranslateUi(self, Browser):
        _translate = QtCore.QCoreApplication.translate
        Browser.setWindowTitle(_translate("Browser", "MainWindow"))
        self.toolButton_back.setText(_translate("Browser", "..."))
        self.toolButton_home.setText(_translate("Browser", "..."))
        self.toolButton_back_refresh.setText(_translate("Browser", "..."))
        self.toolButton_search.setText(_translate("Browser", "..."))
import icons_rc
